server:
  port: 8080
eureka:
  instance:
    hostname: localhost
  client:
    #作为EurekaServer
    register-with-eureka: false
    #是否获取服务信息
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-server